### ISSUE TITLE
Incorrect death counts

### ISSUE THREAD

**Issue by ht-weng** [M3IT/COVID-19_Data#10] opened 2022-02-07 02:54 UTC
Hi Matt,
Thanks for the great work.
I found that the recent death counts in `Data/COVID_AU_state.csv` are all zeros, which I think is incorrect. Would you be able to fix them? Cheers.

**Comment by M3IT** [comment] 2022-02-07 11:55
Hi Ht,
Thanks for letting me know. The issue is now fixed.
Matt

**Closed by M3IT** 2022-02-07 11:55 UTC
